[package]
name = "ripissue"
version = "0.1.0"
edition = "2021"
about = "this is cargo about"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.2", features = ["derive"] }
slugify = "0.1.0"
